#=== FATIAMENTO DE STRING ===

#frase = 'Curso em Vídeo Python'

#print(frase[0:5]) - DA POSIÇÃO 0 ATÉ A 5 POSIÇÃO - CORTANDO O ULTIMO NUMERO
#print(frase[9:21:2]) - DA POSIÇÃO 9 ATÉ A 21 - PULANDO DE 2 EM 2 
#print(frase[:5]) - ELE STARTA DA POSIÇÃO 0 ATÉ ONDE FOI DEFINIDO
#print(frase[15:]) - ELE COMEÇA DA POSIÇÃO 15 - E TERMINA NA ULTIMA POSIÇÃO
#print(frase[9::3]) - COMEÇAR DA POSIÇÃO 9 E VAI ATÉ O FINAL PULANDO DE 3 EM 3

#=== ANÁLISE ===

#len(frase) - MENSURA A QUANTIDADE DE ESPAÇO DA VARIÁVEL
#frase.count('o') - CONTAR QUANTAS VEZES APARECE A LETRA 'O' MINUSCULO
#frase.count('o', 0, 13) - CONTAR QUANTAS LETRAS 'O' TEM NO PERIODO MENCIONADO
#frase.find('deo') - ENCONTRAR A LETRA/FRASE E A POSIÇÃO QUE ELE COMEÇA
#frase.find('Android') - VAI RETORNAR -1 POIS NÃO FOI ENCONTRADO NA STRING
#'Curso' in frase - VAI RETORNAR TRUE OU FALSE SE EXISTE A PALAVRA 'CURSO' NA STRING

#=== TRANSFORMAÇÃO ===

#frase.replace('Python', 'Android') - SUBSTITUIR A PALAVRA MENCIONADA NA PRIMEIRA CAIXA, PELA SEGUNDA
#frase.upper() - DEIXA TUDO EM MAIUSCULO
#frase.lower() - DEIXA TUDO EM MINUSCULO
#frase.capitalize() - DEIXA SÓ O PRIMEIRO CARACTERE EM MINUSCULO
#frase.title() - ANALISA OS ESPAÇOS E ADICIONA LETRAS MAIUSCULAS
#frase.strip() - REMOVE OS ESPAÇOS ANTES E DEPOIS DA FRASE/PALAVRA
#frase.rstrip() - REMOVE SOMENTE OS ESPAÇOS DO LADO DIREITO (R de right)
#frase.lstrip() - REMOVE SOMENTE OS ESPAÇOS DO LADO ESQUERDO (L de left)

#=== DIVISÃO ===

#frase.split() - VAI PEGAR OS ESPAÇOS VAZIOS E COMEÇAR UMA OUTRA LISTA 
 
 #=== JUNÇÃO ===

#'-'.join(frase) - FAZ A JUNÇÃO DA FRASE USANDO O ARGUMENTO '-' QUE DEFINIMOS

