# POTÊNCIA (**) OU POW(2,4) 
# DIVISÃO INTEIRA (//)
# RESTO DA DIVISÃO (%)
# CRIAR A RAIZ QUADRADA DE UM NÚMERO É A MESMA COISA QUE EU FAZER A POTÊNCIA DELE ELEVADA A 1/2
# CRIAR A RAIZ CÚBICA DE UM NÚMERO É A MESMA COISA QUE EU FAZER A POTÊNCIA DELE ELEVADA A 1/3
#{:20} ESCREVER QUALQUER COISA EM 20 CARACTERES
#{:<20} ALINHAR À ESQUERDA
#{:>20} ALINHAR À DIREITA
#{:^20} CENTRALIZAR 

nome = input("Digite seu nome: ")
print("Prazer em te conhecer, {:^20}!".format(nome))
